In [9]:
import numpy as np

In [10]:
p_1 = [49.89, 62.02, -202.97]
p_2 = [89.98, 171.81, 401.22]

n = np.cross(p_1, p_2)
n_hat = n/np.sqrt(np.dot(n, n))
x = [1, 0, 0]

In [19]:
v = np.cross(n_hat, x)
s = np.sqrt(np.dot(v, v))
c = np.dot(x, n_hat)



[-0.          0.04211028  0.53893809]


In [37]:
v_mat = np.array([[0,-v[2],v[1]], [v[2],0,-v[0]], [-v[1],v[0],0]])
v_mat_sq = np.matmul(v_mat, v_mat)
I = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

fact = (1-c)/np.power(s,2)
print(fact)

0.5430968727014941


In [38]:
R = np.add(I, v_mat)
R = np.add(R, v_mat_sq*fact)

In [39]:
print(R)

[[ 0.84129213 -0.53893809  0.04211028]
 [ 0.53893809  0.8422552   0.01232549]
 [-0.04211028  0.01232549  0.99903694]]


In [ ]:
print(np.matmul(R, p_3))